modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="the_realm_of_dreams"
version="0.1"
displayName="The Realm of Dreams"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Ryan, MCreator"
description='''
Whatchu think?
'''

[[dependencies.the_realm_of_dreams]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




